### ISSUE TITLE
GPU HANG + segfault in libflashplayer.so

### ISSUE THREAD

**Issue by duud** [i-rinat/libvdpau-va-gl#45]
Often after I've found an interesting video on youtube.com I pause the video in the browser, copy the url and use mpv to watch it. This worked well until recently I tried your freshplayerplugin. After trying it I went back to my previous setup (flash 11 + libvdpau-va-gl) since I'm not getting automatic updates for pepperflash on my distro. I'm not sure if this is related to my test with freshplayerplugin but now every time when I'm starting mpv (which also uses vaapi) I'm getting a GPU HANG and a segfault in libflashplayer.so. Here is some data:

When I pause a video on youtube.com I'm getting this VDPAU_LOG:
```
[VS] {full} VdpOutputSurfaceRenderBitmapSurface destination_surface=4, destination_rect=(0,0,854,510),
           source_surface=6, source_rect=(0,0,854,510)
           blend_state.blend_factor_source_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
           blend_state.blend_factor_source_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
           blend_state.blend_equation_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_state.blend_equation_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_constant = (   0,000000,    0,000000,    0,000000,    0,000000)
           flags = VDP_OUTPUT_SURFACE_RENDER_ROTATE_0
           colors=[]
[VS] {full} VdpPresentationQueueDisplay presentation_queue=3, surface=4, clip_width=0, clip_height=0,
           earliest_presentation_time=0
[VS] {full} VdpPresentationQueueBlockUntilSurfaceIdle presentation_queue=3, surface=5
[VS] {full} VdpOutputSurfaceRenderOutputSurface destination_surface=5, destination_rect=(0,0,854,480),
           source_surface=7, source_rect=(0,0,854,480)
           blend_state.blend_factor_source_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ZERO
           blend_state.blend_factor_source_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ZERO
           blend_state.blend_equation_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_state.blend_equation_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_constant = (   0,000000,    0,000000,    0,000000,    0,000000)
           flags = VDP_OUTPUT_SURFACE_RENDER_ROTATE_0
           colors=[]
[VS] {full} VdpOutputSurfaceRenderBitmapSurface destination_surface=5, destination_rect=(0,0,854,510),
           source_surface=6, source_rect=(0,0,854,510)
           blend_state.blend_factor_source_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
           blend_state.blend_factor_source_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
           blend_state.blend_equation_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_state.blend_equation_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_constant = (   0,000000,    0,000000,    0,000000,    0,000000)
           flags = VDP_OUTPUT_SURFACE_RENDER_ROTATE_0
           colors=[]
[VS] {full} VdpPresentationQueueDisplay presentation_queue=3, surface=5, clip_width=0, clip_height=0,
           earliest_presentation_time=0
[VS] {full} VdpPresentationQueueBlockUntilSurfaceIdle presentation_queue=3, surface=4
[VS] {full} VdpOutputSurfaceRenderOutputSurface destination_surface=4, destination_rect=(0,0,854,480),
           source_surface=7, source_rect=(0,0,854,480)
           blend_state.blend_factor_source_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ZERO
           blend_state.blend_factor_source_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ZERO
           blend_state.blend_equation_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_state.blend_equation_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_constant = (   0,000000,    0,000000,    0,000000,    0,000000)
           flags = VDP_OUTPUT_SURFACE_RENDER_ROTATE_0
           colors=[]
```
This sequence repeats for ever.

Then I start mpv and I'm getting this:
```
.
.
.
[VS] {full} VdpOutputSurfaceRenderBitmapSurface destination_surface=5, destination_rect=(0,0,854,510),
           source_surface=6, source_rect=(0,0,854,510)
           blend_state.blend_factor_source_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
           blend_state.blend_factor_source_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE
           blend_state.blend_factor_destination_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
           blend_state.blend_equation_color=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_state.blend_equation_alpha=VDP_OUTPUT_SURFACE_RENDER_BLEND_EQUATION_ADD
           blend_constant = (   0,000000,    0,000000,    0,000000,    0,000000)
           flags = VDP_OUTPUT_SURFACE_RENDER_ROTATE_0
           colors=[]
intel_do_flush_locked failed: input/output error

###!!! [Parent][MessageChannel::Call] Error: Channel error: cannot send/recv
```
dmesg:
```
[25870.342018] [drm] stuck on render ring
[25870.346229] [drm] GPU HANG: ecode 5:0:0x9ffdffff, in plugin-containe [12310], reason: Ring hung, action: reset
[25870.346334] [drm:i915_set_reset_status [i915]] *ERROR* gpu hanging too fast, banning!
[25870.358712] drm/i915: Resetting chip after gpu hang
[25870.372973] plugin-containe[12326]: segfault at 7fa59d3586fb ip 00007fa5ad0f32e0 sp 00007fa59bffcb30 error 4 in libflashplayer.so[7fa5acf13000+1189000]
```
Any ideas?

**Comment by i-rinat** [comment]
(Just to be sure.) Browser plugin crashes after you launch mpv? If so, cause must be somewhere in common part. First thought — a kernel driver issue. Or maybe Xorg.

Although there is another possibility. GPU decoding is quite fragile when it gets a damaged input. I saw a lot of both temporary and permanent hangs during development when I fed VA-API driver with a wrong input. In latter case I needed to power off machine and the start again to get it working. So if there is something wrong with libvdpau-va-gl parsing code (actually, it's wrong, as part of H.264 parser was never written), it may leave GPU in a wrong state. However issue would not appear recently, because I didn't change the code for a long time.

**Comment by i-rinat** [comment]
I also saw crashes in intel GL driver, and thought there're bug in that driver, but later found that I have a bug in my code. So it's worth to try to run plugin under Valgrind. There is a trick ([link](https://github.com/i-rinat/freshplayerplugin/blob/master/doc/debugging-guide.md#running-under-valgrind)) which helps to run only `plugin-container` under Valgrind rather than the whole browser.

**Comment by duud** [comment]
Yes, it crashes after launching mpv.
GPU decoding ist disabaled, It stoped working for me recently (EnableLinuxHWVideoDecode=0) , I only use libvdpau-va-gl for accelerated rendereing. (btw. i don't know why accelerated rendering isn't working without libvdpau-va-gl, I think you have more insight here, so do you know why?)

**Comment by i-rinat** [comment]
> why accelerated rendering isn't working without libvdpau-va-gl

The only known hardware accelerated way to output graphics and decode video for Flash 11.2 is VDPAU. It doesn't use platform's OpenGL, therefore without working VDPAU driver Flash falls back to all-software mode.

**Comment by duud** [comment]
Ok thx.

I never used valgrind, it would be nice if you have some time to take a look:
http://expirebox.com/download/81bfce0e26e68ebcac3653416144ecca.html

**Comment by duud** [comment]
Your intuition was right.
Recently arch updated mesa from 10.5.7 to 10.6.0.
I installed 10.5.7, accelerated rendering + decoding is working properly again.

**Comment by i-rinat** [comment]
> take a look

I see nothing wrong there. Multiple use-after-free warnings are due to quirks in glib2.0 code.

**Comment by duud** [comment]
Thank  you.

This is not related but you're the right person to ask :)
Are there any reasons/advantages for using freshplayerplugin+pepperflash?

**Comment by i-rinat** [comment]
> Are there any reasons/advantages for using freshplayerplugin+pepperflash?

During libvdpau-va-gl development I found that NPAPI Flash uses VDPAU only when wmode parameter is equal to either `window` or `direct`. It's the case on Youtube, so it's fine there. But many other sites with other players, and even some embedded videos from Youtube are using wmode=transparent or wmode=opaque, thus forcing Flash to use CPU for all rendering.

To support transparency, NPAPI Flash uses different modes, windowed and windowless. In first case plugin either creates or receives an X Window which it draws at. In second case (windowless), browser creates Pixmaps where plugin paint. Windowless operation mode is required for transparency — browser passes Pixmap already with content, and plugin paints over it. That mode is also required if one wants to paint over plugin instance, display a text, for example, or custom HTML controls. But since with windowless mode one doesn't have a known Window, using of VDPAU is hard, if even possible. That's why Flash falls back to software rendering.

I once thought about creating a proxy plugin to make Flash believe that it always can use VDPAU, but decided to make such proxy for PepperFlash after all. Since I do all the interaction with OS and browser, I'm able to allow Flash to use hardware accelerated rendering regardless of plugin mode.

At the end of the day, freshwrapper can help reduce CPU load, moving some of it to GPU. Or maybe not. It depends. I also heard some people use it where Flash 11.5 is required, and therefore 11.2 doesn't work.

**Comment by duud** [comment]
Very detailed answer, nice.
This information is really usefull so I think it should be put into freshplayerplugin's readme.
Just put a link to your previous post, it's pretty detailed.
