### ISSUE TITLE
Create lists of supported hardware and software.

### ISSUE THREAD

**Issue by DmitryHetman** [i-rinat/libvdpau-va-gl#65]

**Comment by DmitryHetman** [comment]
Should I prefer vaapi over vdpau?

**Comment by i-rinat** [comment]
> supported hardware

I think, almost every Intel GPU came out later than 2010 is capable of hardware video decoding acceleration. Since 2011 they had H.264 capability. Unfortunately, I can't list them all.

> and software

What works, works. Initially, I developed code to support NPAPI Flash, and during development also used MPlayer and mpv, so they should work. Although code changes, so what worked before can stop working now. It's easier to just try than guess.

If it doesn't work, it's a bug, and worth mentioning in the issue tracker. Project doesn't receive as much time as I wanted, but I'm planning to implement all API features eventually.

> Should I prefer vaapi over vdpau?

Most often, you don't have a choice. If you have an Intel GPU, you have native VA-API support. If you have a NVIDIA GPU, you have native VDPAU support. In case you do have a choice, for example, for opensource Radeon drivers, you can select anything you want. There is no much difference between APIs, as they solve the same task.

If you have software which speaks only VDPAU, and hardware, which speaks VA-API, you can use `libvdpau-va-gl` as a traslation layer. If program of your choice supports multiple APIs, choose native one.

> Does it work with wayland?

VDPAU at the moment have no Wayland support. VA-API have Wayland support. `libvdpau-va-gl` implements VDPAU, and therefore is not Wayland-capable.
